const disciplina = "programacao Web";
const quantidadedeAulas = 20;
const estaAprovado = true;
const observacao = null;
let mediaFinal;
console.log(typeof disciplina);
console.log(typeof quantidadedeAulas);
console.log(typeof estaAprovado);
console.log(typeof observacao);
console.log(typeof mediaFinal);
